modLoader="javafml"
loaderVersion="[47,)"
license="Apache 2.0 with Commons Clause"
issueTrackerURL="https://github.com/davo899/CobblemonTrainers/issues"

[[mods]]
modId="cobblemontrainers"
version="${version}"
displayName="CobblemonTrainers"
displayURL="https://github.com/davo899/CobblemonTrainers"
authors="selfdot"
description='''
Adds a trainer battle system to Cobblemon
'''

[[dependencies.cobblemontrainers]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cobblemontrainers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cobblemontrainers]]
    modId="architectury"
    mandatory=true
    versionRange="[9.2.14,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cobblemontrainers]]
    modId="cobblemon"
    mandatory=true
    versionRange="[1.5.2,)"
    ordering="NONE"
    side="BOTH"
